server:
  port: 8001
spring:
  application:
    name: spring-cloud-micro-service-2021-provider   #唯一名称
  cloud:
    nacos:
      discovery:
        server-addr: 172.16.0.35:8848  #Nacos 链接地址
        namespace: 82dd8e34-d3c8-4320-980b-cbc3939365bf #Nacos 命名空间ID
      config:
        server-addr: 172.16.0.35:8848  #Nacos 链接地址
        namespace: 82dd8e34-d3c8-4320-980b-cbc3939365bf #Nacos 命名空间ID
        group: DEFAULT_GROUP  # 默认分组就是DEFAULT_GROUP，如果使用默认分组可以不配置
        file-extension: yml   #默认properties